version: '3'
services:
    php56:
      container_name: php56
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "5600:80"
      volumes:
        - ./apache2/conf:/etc/apache2/sites-enabled
        - ./apache2/www/html:/var/www/html
        - ./apache2/logs:/var/log/apache2
        - ./php/php.ini:/etc/php5/php.ini
      environment:
        - TZ=Asia/Jakarta
      restart: always
