version: '3'
services:
    php56:
      container_name: php56
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "81:80"
        - "444:443"
      volumes:
        - ./apache2/conf:/etc/apache2/sites-enabled
        - ./apache2/www/html:/var/www/html
        - ./apache2/logs:/var/log/apache2
        - ./php/php.ini:/usr/local/etc/php/php.ini
      environment:
        - TZ=Asia/Jakarta
      restart: always
